### ISSUE TITLE
Its faster than zgen/zgenom?

### ISSUE THREAD

**Issue by mecurc** [agkozak/zcomet#7]
Sorry for that stupid question, just interesting :D

**Comment by agkozak** [comment]
It's a very good question, but the answer is a complex one. From what I can tell, they all perform similarly except in one area: "[first command lag"](https://github.com/romkatv/zsh-bench#how-it-works) -- the amount of time before the first typed command begins to be executed. `zgen` is a little slower than `zcomet`, and `zgenom` is a little faster than `zcomet`:

![image](https://user-images.githubusercontent.com/7599319/139562248-b752b22d-367f-4ef3-8690-0a8e274021dd.png)

(I used the [`zsh-bench`](https://github.com/romkatv/zsh-bench) benchmark program to do the calculations -- you should read the `zsh-bench` essay if you're interested in how to assess whether specific benchmarks are meaningful. `diy++` is just a very well designed `.zshrc` with no plugin manager.)

The `zgen`/`zgenom` paradigm is very different from that of `zcomet`. The former two plugin managers use a cache script so that they don't have to recalculate how to load plugins every time they run. They also use (by default, at least) `compinit -C` to largely bypass `compinit`'s time-consuming activities. That seems to work quite well for many people, but it means extra steps if you make a change to your setup.

`zcomet` is more dynamic; if you change your `.zshrc` or type `zcomet load author/plugin` at the command line, you'll see the change immediately -- there's no need for a `save`, `apply`, or `reset` command. So `zcomet`'s model takes convenience as well as speed into account.

Let me know if you have any other questions.

**Comment by agkozak** [comment]
The raw data from 64 iterations of zsh-bench:
```
==> starting ubuntu:impish in docker ...
==> setting up a container ...
==> benchmarking diy++ ...
creates_tty=1
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=14.229
first_command_lag_ms=125.064
command_lag_ms=4.493
input_lag_ms=23.953
exit_time_ms=38.224
==> benchmarking zcomet ...
creates_tty=1
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=15.902
first_command_lag_ms=131.435
command_lag_ms=4.593
input_lag_ms=23.735
exit_time_ms=43.216
==> benchmarking zgen ...
creates_tty=1
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=15.907
first_command_lag_ms=140.969
command_lag_ms=4.515
input_lag_ms=26.990
exit_time_ms=53.481
==> benchmarking zgenom ...
creates_tty=1
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=15.911
first_command_lag_ms=113.059
command_lag_ms=4.509
input_lag_ms=26.191
exit_time_ms=24.928
```
